version: '3'
services:
    api:
        build: .
        image: dockernode
        container_name: 'app'
        ports:
            - '${PORT}:3000'
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./:/usr/src
        working_dir: /usr/src/
    db:
        image: postgis/postgis:16-3.4
        container_name: 'postgres'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '${DB_PORT}:5432'
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
    pgdata:
