services:
    api1:
        build: .
        image: dockernode
        container_name: 'app1'
        ports:
            - '${PORT_API1}:3000'
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./:/usr/src
        working_dir: /usr/src/
    api2:
        build: .
        image: dockernode
        container_name: 'app2'
        ports:
            - '${PORT_API2}:3000'
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./:/usr/src
        working_dir: /usr/src/
    db:
        image: postgis/postgis:16-3.4
        container_name: 'postgres'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '${DB_PORT}:5432'
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2

volumes:
    pgdata:
