version: '3'
services:
    api:
        image: dockernode
        container_name: "app"
        ports:
            - '3000:3000'
        links:
            - link-db
        volumes:
            - ./:/usr/src/app
    link-db:
        image: "postgres"
        container_name: "postgres"
        volumes:
            - ./postgres:/var/lib/postgres
        ports:
            - "${DB_PORT}:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
